<?php
/**
 * Compile script to update the plugin code in the HTML file.
 *
 * This script reads the plugin code from play-editor.php and injects it
 * into the source.html file, creating an updated index.html.
 *
 * @package play-editor
 */

// phpcs:disable WordPress.WP.AlternativeFunctions
// phpcs:disable WordPress.Security.EscapeOutput

$plugin_code = file_get_contents( 'play-editor.php' );

// Update the plugin variable in index.html.
$index_html = file_get_contents( 'source.html' );

// Replace the plugin variable in the HTML.
$updated_html = preg_replace(
	'/const plugin = ``;/',
	'const plugin = `' . str_replace(
		array( '$', '</script>' ),
		array( '\\$', '<\\/script>' ),
		$plugin_code
	) . '`;',
	$index_html
);

$updated_html = '<!-- This is an autogenerated file - Please do not change - ' . gmdate( 'c' ) . " -->\n" . $updated_html;

file_put_contents( 'index.html', $updated_html );
echo 'http://' . htmlspecialchars( realpath( 'index.html' ), ENT_QUOTES, 'UTF-8' ) . "\n";
